export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  AFFILIATE = 'AFFILIATE',
  ADVENTURER = 'ADVENTURER',
  INDEPENDENT_AGENT = 'INDEPENDENT_AGENT',
  COOPERATE_AGENT = 'COOPERATE_AGENT',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum AdventureStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum AdventureLevel {
  MEDIUM = 'MEDIUM',
  CHALLENGING = 'CHALLENGING',
  HARD = 'HARD',
}

export enum AccessType {
  LOCKED = 'LOCKED',
  UNLOCKED = 'UNLOCKED',
}

export enum CallStatus {
  SCHEDULED = 'SCHEDULED',
  EXPIRED = 'EXPIRED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ContractStatus {
  SIGNED = 'SIGNED',
  NOT_SIGNED = 'NOT_SIGNED',
}

export enum EventStatus {
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  ATTENDED = 'ATTENDED',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
}

export enum TripType {
  HIKING = 'HIKING',
  TREKKING = 'TREKKING',
  SAFARI = 'SAFARI',
  WATER_SPORTS = 'WATER_SPORTS',
  WINTER_SPORTS = 'WINTER_SPORTS',
  CULTURAL = 'CULTURAL',
  WELLNESS = 'WELLNESS',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  VOLUNTEERING = 'VOLUNTEERING',
  EXPEDITION = 'EXPEDITION',
  ROAD_TRIP = 'ROAD_TRIP',
  BACKPACKING = 'BACKPACKING',
  EXTREME_SPORTS = 'EXTREME_SPORTS',
  WILDLIFE = 'WILDLIFE',
  URBAN_EXPLORATION = 'URBAN_EXPLORATION',
  CYCLING = 'CYCLING',
  CLIMBING = 'CLIMBING',
  DIVING = 'DIVING',
  SURFING = 'SURFING',
  KAYAKING = 'KAYAKING',
  OTHER = 'OTHER',
}
